using CommandLine;

namespace NuPopulator;

public class Options
{
    [Option(
        "log-level",
        Required = false,
        HelpText = "Set the logging level. Possible values: Trace, Debug, Info, Warn, Error, Critical"
    )]
    public string LogLevel { get; set; } = "Information";

    [Value(0, Required = true, HelpText = "Input json file generated by NuExporter.")]
    public string JsonPath { get; set; } = string.Empty;
}
